apiVersion: apps/v1
kind: Deployment
metadata:
  name: bould-d
  labels:
    app: bould
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bould
  template:
    metadata:
      labels:
        app: bould
    spec:
      imagePullSecrets:
        - name: regcrednheek
      containers:
        - name: bould
          image: reg.nheek.com/nheek/bould:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 2
            timeoutSeconds: 2
            failureThreshold: 10
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 2
            failureThreshold: 10
