apiVersion: apps/v1
kind: Deployment
metadata:
  name: bould-deployment
  namespace: static
  labels:
    app: bould
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bould
  template:
    metadata:
      labels:
        app: bould
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: bould
        image: nheek/bould:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "30Mi"