apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bould-hpa
  namespace: static
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bould-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
